name: Get Blogs

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */1 * * *"

jobs:
  get-blogs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Github Readme Blog Post Action
        uses: nexensys/github-readme-blog-post-action@v1
        with:
          feed_urls: "https://www.ilean.me/rss.xml"
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Save Generated Blog Posts
          skip_checkout: true
